# Generated by Django 6.0.2 on 2026-02-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0006_videorecording'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorecording',
            name='question_text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
