# Generated by Django 6.0.2 on 2026-02-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_askedquestion_delete_interviewfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='askedquestion',
            name='level',
            field=models.CharField(default='beginner', max_length=50),
            preserve_default=False,
        ),
    ]
