# Generated by Django 6.0.2 on 2026-02-17 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0009_interviewanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewanswer',
            name='correct_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewanswer',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
