# Generated by Django 6.0.2 on 2026-02-17 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0010_interviewanswer_correct_answer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='practiceday',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='practiceday',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='practiceday',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='practiceday',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='practiceday',
            name='questions_attempted',
        ),
    ]
